### ISSUE TITLE
How to perform object classification?

### ISSUE THREAD

**Issue by sheerun** [jigsawxyz/react-native-coreml-image#1]
For now I was only able to succeed classification, what about [object detection](https://apple.github.io/turicreate/docs/userguide/object_detection/introduction.html)?

**Comment by darylrowland** [comment]
Hi, we've not yet adapted this to object detection. I think it should be possible to do though - if you fancy having a go at it?

Note the training of the data would be a bit more complicated, e.g. https://github.com/apple/turicreate/blob/master/userguide/object_detection/introduction.md

**Comment by sheerun** [comment]
I tried to do so but failed. I get strange errors and I'm unable to get proper output from model (proper type casting etc.). I'm not Swift / ObjectiveC developer, so unfortunately I can't easily help here :(
