### ISSUE TITLE
Can I train my model?

### ISSUE THREAD

**Issue by stoneWeb** [jigsawxyz/react-native-coreml-image#3]
How do I integrate the training model?
Can it detect multiple objects at the same time, including coordinate information?

**Comment by darylrowland** [comment]
Hey,

The medium article here: https://medium.com/jigsaw-xyz/realtime-image-recognition-in-reactnative-with-coreml-24ed7d414f23 explains how to integrate the model

At the moment... it just detects the predominant object in the image, so no coordinates
