### ISSUE TITLE
Use Front Camera?

### ISSUE THREAD

**Issue by trev91** [jigsawxyz/react-native-coreml-image#5]
Is there a way to use the front camera? By "front", I guess I mean the camera that faces the user (as in "selfie" camera). Thanks.

**Comment by darylrowland** [comment]
It should be possible. A quick scan of the docs looks like we'd need to use this: https://developer.apple.com/documentation/avfoundation/avcapturedeviceposition?changes=_5&language=objc

Feel free to make a pull request if you do get this working?
