### ISSUE TITLE
CoreMLImage.xcodeproj errors

### ISSUE THREAD

**Issue by rachit2jain** [jigsawxyz/react-native-coreml-image#6]
Hi, 

I have been trying to use the library in my ejected app (to ExpoKit). I followed all the instruction as mentioned in the tutorial on medium. Before react-native link, everything is good and the app is working fine (obviously except the CoreML thing) After I run react-native link, an Xcode project is created under Libraries folder named CoreMLImage.xcodeproj. Now when I try to compile the project, there are some errors such as <React/RCTView.h> not found etc. I solved all these kind of error by using #import "RCTView.h" instead of #import <React/RCTView.h>.

The problem is that I am not able to solve #import <yoga/Yoga.h>. I have all the forums available. Can you please help me? It will be really helpful.

**Comment by ami9000** [comment]
@rachit2jain Did you solve this? How?
