### ISSUE TITLE
Native component for CoreMLImage does not exist 

### ISSUE THREAD

**Issue by rachit2jain** [jigsawxyz/react-native-coreml-image#7]
Hi, I am trying to use the library.
The issue is that sometimes, it works as expected but when I disconnect my iPhone and try to run it again, the error `Native component for CoreMLImage does not exist` shows up. My project was made using CRNA and is now ejected to ExpoKit. Any idea why this is happening?

The error is located on line 43 of CoreMLImage.ios.js file.

**Comment by darylrowland** [comment]
From the error message, looks like you have not managed to link your code to the native code correctly. I've honestly not used ExpoKit/CRNA before, so I'm going to close this issue as it seems like it is an issue with that and not this module.
